<?php
/**
 * Created by PhpStorm.
 * User: Samir Subašić
 * Date: 11.12.2017
 * Time: 14:08
 */

function progressBar($done, $total) {
    $perc = floor(($done / $total) * 100);

    static $Ten = true;
    static $Twenty = true;
    static $Thirty = true;
    static $Forty = true;
    static $Fifty = true;
    static $Sixty = true;
    static $Seventy = true;
    static $Eighty = true;
    static $Ninety = true;
    static $Hundred = true;

    switch ($perc) {
        case 10:
            $StrToCmd = $Ten ? "10% ... " : "";
            $Ten = false;
            echo $StrToCmd;
            break;
        case 20:
            $StrToCmd = $Twenty ? "20% ... " : "";
            $Twenty = false;
            echo $StrToCmd;
            break;
        case 30:
            $StrToCmd = $Thirty ? "30% ... " : "";
            $Thirty = false;
            echo $StrToCmd;
            break;
        case 40:
            $StrToCmd = $Forty ? "40% ... " : "";
            $Forty = false;
            echo $StrToCmd;
            break;
        case 50:
            $StrToCmd = $Fifty ? "50% ... " : "";
            $Fifty = false;
            echo $StrToCmd;
            break;
        case 60:
            $StrToCmd = $Sixty ? "60% ... " : "";
            $Sixty = false;
            echo $StrToCmd;
            break;
        case 70:
            $StrToCmd = $Seventy ? "70% ... " : "";
            $Seventy = false;
            echo $StrToCmd;
            break;
        case 80:
            $StrToCmd = $Eighty ? "80% ... " : "";
            $Eighty = false;
            echo $StrToCmd;
            break;
        case 90:
            $StrToCmd = $Ninety ? "90% ... " : "";
            $Ninety = false;
            echo $StrToCmd;
            break;
        case 100:
            $StrToCmd = $Hundred ? "100%" : "";
            $Hundred = false;
            echo $StrToCmd;
            break;
    }
}

// exec  mysqli connection
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "PracticalParseFile";
// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);

// test mysql connection
function test_mysqli_conn() {
    $servername = "localhost";
    $username = "root";
    $password = "";
    $dbname = "PracticalParseFile";
    // Create connection
    $conn = new mysqli($servername, $username, $password, $dbname);

    // Check connection
    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error .PHP_EOL);
    }

    echo "Connected successfully" .PHP_EOL;
}

// reads data from CSV File and returns no of rows
//$FileToParse = array();
function readDataFromCSVFile($filename) {
    if (($handle = fopen($filename, "r")) !== FALSE) {
        while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
            $FileToParse[] = $data;
        }
        fclose($handle);
    }
    return $FileToParse;
}

// read csv file
$ParsedDataFile = readDataFromCSVFile('csv/project.html');

// read name file, generated by http://listofrandomnames.com/index.cfm
// PS: had to use https://convert.town/column-to-comma-separated-list,
// because assholes at Microsoft don't uderstand what Save As CSV file means!!! It's not separated by space and new line!
// Generated list from ListOfRandomNames was stuck together Name and Surname, splited in Excel 2016, rest read line above!
$NamesDataFile = readDataFromCSVFile('csv/Names.csv');

// read surname file, generated by http://listofrandomnames.com/index.cfm
$SurnamesDataFile = readDataFromCSVFile('csv/Surnames.csv');

//debug - adding name and surname
/*
$rand_name = array_rand($NamesDataFile[0], 1);
$rand_surname = array_rand($SurnamesDataFile[0], 1);

echo "Name and Surname .... " . $NamesDataFile[0][$rand_name] .' '.$SurnamesDataFile[0][$rand_surname] . PHP_EOL;
*/

// add names and surnames at the end of file
foreach ($ParsedDataFile as $parsedLine) {
    $rand_name = array_rand($NamesDataFile[0], 1);
    $rand_surname = array_rand($SurnamesDataFile[0], 1);

    array_push($parsedLine,  $NamesDataFile[0][$rand_name], $SurnamesDataFile[0][$rand_surname]);

    $ParsedDataFileFinal[] = $parsedLine;
}

//print_r($ParsedDataFileFinal[0]);

//write data to SQL
test_mysqli_conn();

//clean datafile table of previous data
echo "Deleting previous data!" .PHP_EOL;
$conn->query('TRUNCATE datafile');

// add data to datafile table
$posOfImportedRow=1;
foreach ($ParsedDataFileFinal as $parsedLine) {
    $sql = sprintf("INSERT INTO datafile (`VehicleID`, `InhouseSellerID`, `BuyerID`, `ModelID`, `SaleDate`, `BuyDate`, `Name`, `Surname` )
        VALUES (%s, %s, %s, %s, '%s', '%s', '%s', '%s')",
        $parsedLine[0], $parsedLine[1], $parsedLine[2], $parsedLine[3],
        $parsedLine[4], $parsedLine[5], $parsedLine[6], $parsedLine[7]);
    $conn->query($sql);

    progressBar($posOfImportedRow, count($ParsedDataFile));
    $posOfImportedRow++;
}

// TESTING first INSERT
/*
$sql = sprintf("INSERT INTO datafile (`VehicleID`, `InhouseSellerID`, `BuyerID`, `ModelID`, `SaleDate`, `BuyDate`, `Name`, `Surname` )
        VALUES (%s, %s, %s, %s, '%s', '%s', '%s', '%s')",
        $ParsedDataFileFinal[0][0], $ParsedDataFileFinal[0][1], $ParsedDataFileFinal[0][2], $ParsedDataFileFinal[0][3],
        $ParsedDataFileFinal[0][4], $ParsedDataFileFinal[0][5], $ParsedDataFileFinal[0][6], $ParsedDataFileFinal[0][7]);
$conn->query($sql);

$sql = sprintf("INSERT INTO datafile (`VehicleID`, `InhouseSellerID`, `BuyerID`, `ModelID`, `SaleDate`, `BuyDate`, `Name`, `Surname` )
        VALUES (%s, %s, %s, %s, '%s', '%s', '%s', '%s')",
    $ParsedDataFileFinal[1][0], $ParsedDataFileFinal[1][1], $ParsedDataFileFinal[1][2], $ParsedDataFileFinal[1][3],
    $ParsedDataFileFinal[1][4], $ParsedDataFileFinal[1][5], $ParsedDataFileFinal[1][6], $ParsedDataFileFinal[1][7]);
$conn->query($sql);
*/

// close mysqli connection
$conn->close();