<?php
/**
 * Created by PhpStorm.
 * User: Samir Subašić
 * Date: 11.12.2017
 * Time: 14:08
 */

$Procentage = 0;
function simpleProgressBar($done, $total) {
    $perc = floor(($done / $total) * 100);

    global $Procentage;
    if ($perc % 10 == 0 && $Procentage <> $perc) {
        $Procentage = $perc;
        echo $Procentage."% ... ";
    }
}

// exec  mysqli connection
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "PracticalParseFile";
// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);

// test mysql connection
function test_mysqli_conn() {
    // Create connection
    global $servername; global $username; global $password; global $dbname;
    $conn = new mysqli($servername, $username, $password, $dbname);

    // Check connection
    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error .PHP_EOL);
    }

    echo "Connected successfully" .PHP_EOL;
}

// reads data from CSV File and returns no of rows
//$FileToParse = array();
function readDataFromCSVFile($filename) {
    if (($handle = fopen($filename, "r")) !== FALSE) {
        while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
            $FileToParse[] = $data;
        }
        fclose($handle);
    }
    return $FileToParse;
}

// read csv file
$ParsedDataFile = readDataFromCSVFile('csv'.DIRECTORY_SEPARATOR.'project.html');

// read name file, generated by http://listofrandomnames.com/index.cfm
// PS: had to use https://convert.town/column-to-comma-separated-list,
// because assholes at Microsoft don't uderstand what Save As CSV file means!!! It's not separated by space and new line!
// Generated list from ListOfRandomNames was stuck together Name and Surname, splited in Excel 2016, rest read line above!
$NamesDataFile = readDataFromCSVFile('csv'.DIRECTORY_SEPARATOR.'Names.csv');

// read surname file, generated by http://listofrandomnames.com/index.cfm
$SurnamesDataFile = readDataFromCSVFile('csv'.DIRECTORY_SEPARATOR.'Surnames.csv');

//debug - adding name and surname
/*
$rand_name = array_rand($NamesDataFile[0], 1);
$rand_surname = array_rand($SurnamesDataFile[0], 1);

echo "Name and Surname .... " . $NamesDataFile[0][$rand_name] .' '.$SurnamesDataFile[0][$rand_surname] . PHP_EOL;
*/

// add names and surnames at the end of file
foreach ($ParsedDataFile as $parsedLine) {
    $rand_name = array_rand($NamesDataFile[0], 1);
    $rand_surname = array_rand($SurnamesDataFile[0], 1);

    array_push($parsedLine,  $NamesDataFile[0][$rand_name], $SurnamesDataFile[0][$rand_surname]);

    $ParsedDataFileFinal[] = $parsedLine;
}

//print_r($ParsedDataFileFinal[0]);

//write data to SQL
test_mysqli_conn();

//clean datafile table of previous data
echo "Deleting previous data!" .PHP_EOL;
$conn->query('TRUNCATE datafile');

// add data to datafile table
$posOfImportedRow=1;
foreach ($ParsedDataFileFinal as $parsedLine) {
    $sql = sprintf("INSERT INTO datafile (`VehicleID`, `InhouseSellerID`, `BuyerID`, `ModelID`, `SaleDate`, `BuyDate`, `Name`, `Surname` )
        VALUES (%s, %s, %s, %s, '%s', '%s', '%s', '%s')",
        $parsedLine[0], $parsedLine[1], $parsedLine[2], $parsedLine[3],
        $parsedLine[4], $parsedLine[5], $parsedLine[6], $parsedLine[7]);
    $conn->query($sql);

    simpleProgressBar($posOfImportedRow, count($ParsedDataFile));
    $posOfImportedRow++;
}

// TESTING first INSERT
/*
$sql = sprintf("INSERT INTO datafile (`VehicleID`, `InhouseSellerID`, `BuyerID`, `ModelID`, `SaleDate`, `BuyDate`, `Name`, `Surname` )
        VALUES (%s, %s, %s, %s, '%s', '%s', '%s', '%s')",
        $ParsedDataFileFinal[0][0], $ParsedDataFileFinal[0][1], $ParsedDataFileFinal[0][2], $ParsedDataFileFinal[0][3],
        $ParsedDataFileFinal[0][4], $ParsedDataFileFinal[0][5], $ParsedDataFileFinal[0][6], $ParsedDataFileFinal[0][7]);
$conn->query($sql);

$sql = sprintf("INSERT INTO datafile (`VehicleID`, `InhouseSellerID`, `BuyerID`, `ModelID`, `SaleDate`, `BuyDate`, `Name`, `Surname` )
        VALUES (%s, %s, %s, %s, '%s', '%s', '%s', '%s')",
    $ParsedDataFileFinal[1][0], $ParsedDataFileFinal[1][1], $ParsedDataFileFinal[1][2], $ParsedDataFileFinal[1][3],
    $ParsedDataFileFinal[1][4], $ParsedDataFileFinal[1][5], $ParsedDataFileFinal[1][6], $ParsedDataFileFinal[1][7]);
$conn->query($sql);
*/

// close mysqli connection
$conn->close();